from app.repositories.heroes_repository import HeroesRepository
from app.repositories.sidekicks_repository import SidekicksRepository
from app.repositories.villains_repository import VillainsRepository